USE PlayStoreDB;
SELECT DeveloperID FROM Apps WHERE DeveloperID NOT IN (SELECT DeveloperID FROM Developer);
SELECT PublisherID FROM Apps WHERE PublisherID NOT IN (SELECT PublisherID FROM Publishers);
SELECT CategoryID FROM Apps WHERE CategoryID NOT IN (SELECT CategoryID FROM Categories);
DESC Apps;
DESC Developer;
SELECT * FROM Developer;
SELECT * FROM Apps;
SELECT * FROM PUBLISHERS;
SELECT * FROM Categories;
INSERT INTO Developer() values (110,'Whatsapp','Russia',2002);
INSERT INTO Developer() values (111,'Inshort','Landon',2013);
ALTER TABLE Apps ADD CONSTRAINT fk_DeveloperID FOREIGN KEY (DeveloperID) REFERENCES Developer(DeveloperID);
INSERT INTO Publishers() Values (210,'Apple App Store','Cupertino','support@Apple.com'),
								(211,'Oppo App Store','Dongguan','Support@Oppa.com');
ALTER TABLE APPS ADD CONSTRAINT fk_PublisherID FOREIGN KEY (PublisherID) REFERENCES Publishers(PublisherID);
ALTER TABLE APPS DROP FOREIGN KEY fk1_publisherID;
INSERT INTO Categories VALUES (303,'reading',6),(310,'writing',13),(311,'Playing',10);
ALTER TABLE Apps ADD CONSTRAINT fk_categoryID FOREIGN KEY (CategoryID) REFERENCES Categories(CategoryID);
SELECT * FROM Apps WHERE Rating>4.5;
SELECT * FROM Apps WHERE Price=0;
SELECT * FROM Apps WHERE CategoryID=305;
SELECT * FROM Apps WHERE Downloads>5000000;
SELECT * FROM Apps WHERE Rating BETWEEN 4.3 AND 4.7;
SELECT * FROM Apps WHERE Price IN (0,299);
SELECT * FROM Apps WHERE AppName LIKE 'G%';
SELECT * FROM Apps WHERE AppName LIKE 'Google';
SELECT * FROM Apps WHERE Rating>4.0 AND Downloads>5000000;
SELECT * FROM Apps WHERE CategoryID=301 OR CategoryID=305;
SELECT * FROM Apps WHERE NOT AppName LIKE 'G%';
SELECT * FROM Apps WHERE Rating>4.5 AND Downloads>1000000;
SELECT * FROM Developer WHERE DeveloperNAME LIKE '%a%';
SELECT * FROM Apps WHERE Price BETWEEN 0 AND 300;
SELECT * FROM apps WHERE PublisherID IN(201,204);
INSERT INTO Apps VALUE (1012,'Sudoko',112,212,312,4.8,25000,301);
SELECT * FROM Apps WHERE CategoryID!=305;